// Generated by LiveScript 1.5.0
(function(){
  var client_pkg, client_js_list, client_css_list, i$, len$, pkg, client_js, client_css;
  client_pkg = ['jquery', 'snapsvg', 'semantic-ui'];
  client_js_list = [];
  client_css_list = [];
  for (i$ = 0, len$ = client_pkg.length; i$ < len$; ++i$) {
    pkg = client_pkg[i$];
    client_js_list.push({
      expand: true,
      cwd: 'node_modules/' + pkg + '/dist',
      src: '*.js',
      dest: '../js/' + pkg
    });
    client_css_list.push({
      expand: true,
      cwd: 'node_modules/' + pkg + '/dist',
      src: '*.css',
      dest: '../css/' + pkg
    });
  }
  client_js = {
    files: client_js_list
  };
  client_css = {
    files: client_css_list
  };
  module.exports = function(grunt){
    grunt.initConfig({
      copy: {
        js: client_js,
        css: client_css
      },
      pug: {
        src: {
          expand: true,
          src: ['*.pug'],
          dest: '../',
          ext: '.html'
        },
        options: {
          pretty: true
        }
      },
      stylus: {
        src: {
          expand: true,
          src: ['*.styl'],
          dest: '../css/',
          ext: '.css'
        }
      },
      livescript: {
        src: {
          expand: true,
          src: ['*.ls', '!Gruntfile.ls'],
          dest: '../js/',
          ext: '.js'
        },
        options: {
          bare: true
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-pug');
    grunt.loadNpmTasks('grunt-contrib-stylus');
    grunt.loadNpmTasks('grunt-livescript');
    return grunt.registerTask('default', ['pug', 'stylus', 'livescript', 'copy']);
  };
}).call(this);
